version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 rm s3://my-diet-react --recursive
artifacts:
  files:
  - '**/*'
  name: my-diet-react
  base-directory: build